server:
  port: 8090

spring:
  application:
    name: fulfillment
  rsocket:
    server:
      port: 7000
  sleuth:
    sampler:
      probability: 100
  zipkin:
    baseUrl: http://localhost:9411/

wavefront:
  application:
    name: ${spring.application.name}
    service: fulfillment