server:
  port: 8092

spring:
  cloud:
    stream:
      bindings:
        output:
          destination: cs
  application:
    name: payment
  sleuth:
    sampler:
      probability: 100
  zipkin:
    baseUrl: http://localhost:9411/

wavefront:
  application:
    name: ${spring.application.name}
    service: payments